/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ApplicatorHead.gltf --transform 
Files: ApplicatorHead.gltf [1.96MB] > /home/shad/PycharmProjects/javascrypt/nodejs/project_maintenance/public/models/ST-20/ApplicatorHead-transformed.glb [653.1KB] (67%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ApplicatorHead(props) {
  const { nodes, materials } = useGLTF('/models/ST-20/ApplicatorHead-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.DDZRD80100010ipt.geometry} material={materials.PaletteMaterial001} position={[0.199, 0.251, -0.759]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/ApplicatorHead-transformed.glb')
