/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ST-20/ApplicatorHeating.gltf --transform -o src/ApplicatorHeating.jsx 
Files: public/models/ST-20/ApplicatorHeating.gltf [1.11MB] > /home/shad/PycharmProjects/javascrypt/nodejs/project_maintenance/src/ApplicatorHeating-transformed.glb [244.67KB] (78%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ApplicatorHeating(props) {
  const { nodes, materials } = useGLTF('/models/ST-20/ApplicatorHeating-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.NVUVA00100230ipt001.geometry} material={materials.PaletteMaterial001} position={[0.474, 0, -0.588]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('/ApplicatorHeating-transformed.glb')
