/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ConnectorHub.gltf --transform 
Files: ConnectorHub.gltf [473.12KB] > /home/shad/PycharmProjects/javascrypt/nodejs/project_maintenance/public/models/ST-20/ConnectorHub-transformed.glb [243.65KB] (49%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ConnectorHub(props) {
  const { nodes, materials } = useGLTF('/models/ST-20/ConnectorHub-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['DIN_912_-_M3_x_0,5_x_16_x_14,75ipt'].geometry} material={materials.PaletteMaterial001} position={[0.682, 0.032, -0.918]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/ConnectorHub-transformed.glb')
