/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Portal.gltf --transform 
Files: Portal.gltf [7.93MB] > /home/shad/PycharmProjects/javascrypt/nodejs/project_maintenance/public/models/ST-20/Portal-transformed.glb [3.32MB] (58%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Portal(props) {
  const { nodes, materials } = useGLTF('/models/ST-20/Portal-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.SLA0011800000ipt.geometry} material={materials.PaletteMaterial001} position={[0.255, 0.521, -0.983]} rotation={[0, -Math.PI / 2, 0]} />
    </group>
  )
}

useGLTF.preload('/Portal-transformed.glb')
