/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 PortalConstruction.gltf --transform 
Files: PortalConstruction.gltf [3.64MB] > /home/shad/PycharmProjects/javascrypt/nodejs/project_maintenance/public/models/ST-20/PortalConstruction-transformed.glb [562.54KB] (85%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function PortalConstruction(props) {
  const { nodes, materials } = useGLTF('/models/ST-20/PortalConstruction-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['DIN_912_-_M5_x_0,8_x_25_x_23ipt006'].geometry} material={materials.PaletteMaterial001} position={[0.537, 1.337, -1.078]} rotation={[0, 0, Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('/PortalConstruction-transformed.glb')
