/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ProductNest.gltf --transform 
Files: ProductNest.gltf [653.73KB] > /home/shad/PycharmProjects/javascrypt/nodejs/project_maintenance/public/models/ST-20/ProductNest-transformed.glb [176.65KB] (73%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ProductNest(props) {
  const { nodes, materials } = useGLTF('/models/ST-20/ProductNest-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.GEPT030100000_4ipt.geometry} material={materials.PaletteMaterial001} position={[0.451, 0, -0.223]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('/ProductNest-transformed.glb')
