/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ST-20/SealingDosageControl.gltf --transform -o src/SealingDosageControl.jsx 
Files: public/models/ST-20/SealingDosageControl.gltf [8.41MB] > /home/shad/PycharmProjects/javascrypt/nodejs/project_maintenance/src/SealingDosageControl-transformed.glb [961.29KB] (89%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function SealingDosageControl(props) {
  const { nodes, materials } = useGLTF('/models/ST-20/SealingDosageControl-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['DIN_912_-_M5_x_0,8_x_20_x_18ipt043'].geometry} material={materials.PaletteMaterial001} position={[0.202, 0.024, -0.643]} rotation={[-Math.PI, 0, Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('/SealingDosageControl-transformed.glb')
