/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ServoZaxis.gltf --transform 
Files: ServoZaxis.gltf [342.34KB] > /home/shad/PycharmProjects/javascrypt/nodejs/project_maintenance/public/models/ST-20/ServoZaxis-transformed.glb [102.84KB] (70%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ServoZaxis(props) {
  const { nodes, materials } = useGLTF('/models/ST-20/ServoZaxis-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['DIN_912_-_M5_x_0,8_x_20_x_18ipt030'].geometry} material={materials.PaletteMaterial001} position={[0.303, 0.727, -0.924]} rotation={[-Math.PI, 1.546, Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('/ServoZaxis-transformed.glb')
