/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ServoYaxis.gltf --transform 
Files: ServoYaxis.gltf [289.67KB] > /home/shad/PycharmProjects/javascrypt/nodejs/project_maintenance/public/models/ST-20/ServoYaxis-transformed.glb [60.82KB] (79%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ServoYaxis(props) {
  const { nodes, materials } = useGLTF('/models/ST-20/ServoYaxis-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['DIN_912_-_M5_x_0,8_x_12_x_10ipt026'].geometry} material={materials.mat_0} position={[0.647, 0.275, -0.996]} />
      <mesh geometry={nodes['BM070-VM-00ipt006'].geometry} material={materials.mat_1} position={[0.571, 0.248, -0.969]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes['BM070-VM-00ipt009'].geometry} material={materials.mat_2} position={[0.571, 0.248, -0.969]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.SLM0010236110ipt001.geometry} material={materials.mat_3} position={[0.66, 0.203, -1.034]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('/ServoYaxis-transformed.glb')
