/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ServoXaxis.gltf --transform 
Files: ServoXaxis.gltf [289.63KB] > /home/shad/PycharmProjects/javascrypt/nodejs/project_maintenance/public/models/ST-20/ServoXaxis-transformed.glb [60.78KB] (79%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ServoXaxis(props) {
  const { nodes, materials } = useGLTF('/models/ST-20/ServoXaxis-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['DIN_912_-_M5_x_0,8_x_12_x_10ipt022'].geometry} material={materials.mat_0} position={[0.061, 0.565, -0.911]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
      <mesh geometry={nodes['BM070-VM-00ipt'].geometry} material={materials.mat_1} position={[0.087, 0.64, -0.885]} rotation={[-Math.PI, 0, 0]} />
      <mesh geometry={nodes['BM070-VM-00ipt003'].geometry} material={materials.mat_2} position={[0.087, 0.64, -0.885]} rotation={[-Math.PI, 0, 0]} />
      <mesh geometry={nodes.SLM0010236110ipt.geometry} material={materials.mat_3} position={[0.022, 0.552, -0.84]} />
    </group>
  )
}

useGLTF.preload('/ServoXaxis-transformed.glb')
